[package]
name = "or_panic"
version = "1.0.0"
edition = "2021"
authors = ["Trin Wasinger"]
license = "MIT"
description = "Extract ok values from Results or panic with the contained error."

[dependencies]
